version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: userauth-service-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: userauthservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin759
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
